"""add_crescimento_renda_reajuste_to_user_financial_profile

Revision ID: 43105e4ec502
Revises: m8n9o0p1q2r3
Create Date: 2026-03-02 00:32:04.063310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43105e4ec502'
down_revision: Union[str, Sequence[str], None] = 'm8n9o0p1q2r3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ignorar_estabelecimentos')
    op.drop_table('duplicados_temp')
    op.drop_table('categories')
    op.drop_table('grupo_config')
    op.drop_index(op.f('ix_plano_compromissos_user_id'), table_name='plano_compromissos')
    op.drop_table('plano_compromissos')
    op.drop_table('budget_planning_backup_20260115_204836')
    op.drop_table('audit_log')
    op.drop_table('budget_planning_backup_20260115_204445')
    op.drop_table('refresh_tokens')
    op.drop_table('error_codes')
    op.drop_table('base_padroes_backup_20260114_144652')
    op.drop_table('estabelecimento_logo')
    op.drop_table('bank_format_compatibility_backup_20260109_185955')
    op.drop_table('budget_categorias_config')
    op.drop_table('user_relationships')
    op.create_index(op.f('ix_base_expectativas_id'), 'base_expectativas', ['id'], unique=False)
    op.create_index(op.f('ix_base_expectativas_id_parcela'), 'base_expectativas', ['id_parcela'], unique=False)
    op.create_index(op.f('ix_base_expectativas_status'), 'base_expectativas', ['status'], unique=False)
    op.create_index(op.f('ix_base_grupos_config_nome_grupo'), 'base_grupos_config', ['nome_grupo'], unique=False)
    op.create_index(op.f('ix_base_grupos_template_id'), 'base_grupos_template', ['id'], unique=False)
    op.create_index(op.f('ix_base_marcacoes_id'), 'base_marcacoes', ['id'], unique=False)
    op.create_index(op.f('ix_base_marcacoes_template_id'), 'base_marcacoes_template', ['id'], unique=False)
    op.drop_index(op.f('ix_base_padroes_estabelecimento_user'), table_name='base_padroes')
    op.drop_index(op.f('ix_budget_planning_ativo'), table_name='budget_planning')
    op.alter_column('expectativas_mes', 'tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'debito'::character varying"))
    op.create_index(op.f('ix_expectativas_mes_id'), 'expectativas_mes', ['id'], unique=False)
    op.drop_column('investimentos_aportes_extraordinarios', 'user_id')
    op.drop_index(op.f('idx_cenario_projecao_cenario'), table_name='investimentos_cenario_projecao')
    op.create_index(op.f('ix_investimentos_cenario_projecao_cenario_id'), 'investimentos_cenario_projecao', ['cenario_id'], unique=False)
    op.create_index(op.f('ix_investimentos_cenario_projecao_id'), 'investimentos_cenario_projecao', ['id'], unique=False)
    op.alter_column('investimentos_cenarios', 'extras_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('investimentos_historico', 'user_id')
    op.create_index(op.f('ix_investimentos_transacoes_anomes'), 'investimentos_transacoes', ['anomes'], unique=False)
    op.create_index(op.f('ix_investimentos_transacoes_data'), 'investimentos_transacoes', ['data'], unique=False)
    op.create_index(op.f('ix_investimentos_transacoes_id'), 'investimentos_transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_investimentos_transacoes_investimento_id'), 'investimentos_transacoes', ['investimento_id'], unique=False)
    op.create_index(op.f('ix_investimentos_transacoes_tipo'), 'investimentos_transacoes', ['tipo'], unique=False)
    op.create_index(op.f('ix_investimentos_transacoes_user_id'), 'investimentos_transacoes', ['user_id'], unique=False)
    op.alter_column('journal_entries', 'is_demo',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('plano_metas_categoria_user_id_grupo_ano_mes_key'), 'plano_metas_categoria', type_='unique')
    op.create_index(op.f('ix_plano_metas_categoria_id'), 'plano_metas_categoria', ['id'], unique=False)
    op.create_unique_constraint('uq_plano_metas_user_grupo_ano_mes', 'plano_metas_categoria', ['user_id', 'grupo', 'ano', 'mes'])
    op.drop_column('preview_transacoes', 'TemParcela')
    op.drop_column('preview_transacoes', 'ValidarIA')
    op.drop_column('preview_transacoes', 'IgnorarDashboard')
    op.add_column('user_financial_profile', sa.Column('crescimento_renda', sa.Float(), nullable=True))
    op.add_column('user_financial_profile', sa.Column('reajuste_mes', sa.Integer(), nullable=True))
    op.add_column('user_financial_profile', sa.Column('reajuste_ano', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('user_financial_profile_user_id_key'), 'user_financial_profile', type_='unique')
    op.drop_index(op.f('ix_user_financial_profile_user_id'), table_name='user_financial_profile')
    op.create_index(op.f('ix_user_financial_profile_user_id'), 'user_financial_profile', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_financial_profile_id'), 'user_financial_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_financial_profile_id'), table_name='user_financial_profile')
    op.drop_index(op.f('ix_user_financial_profile_user_id'), table_name='user_financial_profile')
    op.create_index(op.f('ix_user_financial_profile_user_id'), 'user_financial_profile', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_financial_profile_user_id_key'), 'user_financial_profile', ['user_id'])
    op.drop_column('user_financial_profile', 'reajuste_ano')
    op.drop_column('user_financial_profile', 'reajuste_mes')
    op.drop_column('user_financial_profile', 'crescimento_renda')
    op.add_column('preview_transacoes', sa.Column('IgnorarDashboard', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('preview_transacoes', sa.Column('ValidarIA', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('preview_transacoes', sa.Column('TemParcela', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_plano_metas_user_grupo_ano_mes', 'plano_metas_categoria', type_='unique')
    op.drop_index(op.f('ix_plano_metas_categoria_id'), table_name='plano_metas_categoria')
    op.create_unique_constraint(op.f('plano_metas_categoria_user_id_grupo_ano_mes_key'), 'plano_metas_categoria', ['user_id', 'grupo', 'ano', 'mes'])
    op.alter_column('journal_entries', 'is_demo',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_investimentos_transacoes_user_id'), table_name='investimentos_transacoes')
    op.drop_index(op.f('ix_investimentos_transacoes_tipo'), table_name='investimentos_transacoes')
    op.drop_index(op.f('ix_investimentos_transacoes_investimento_id'), table_name='investimentos_transacoes')
    op.drop_index(op.f('ix_investimentos_transacoes_id'), table_name='investimentos_transacoes')
    op.drop_index(op.f('ix_investimentos_transacoes_data'), table_name='investimentos_transacoes')
    op.drop_index(op.f('ix_investimentos_transacoes_anomes'), table_name='investimentos_transacoes')
    op.add_column('investimentos_historico', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('investimentos_cenarios', 'extras_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_investimentos_cenario_projecao_id'), table_name='investimentos_cenario_projecao')
    op.drop_index(op.f('ix_investimentos_cenario_projecao_cenario_id'), table_name='investimentos_cenario_projecao')
    op.create_index(op.f('idx_cenario_projecao_cenario'), 'investimentos_cenario_projecao', ['cenario_id'], unique=False)
    op.add_column('investimentos_aportes_extraordinarios', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_expectativas_mes_id'), table_name='expectativas_mes')
    op.alter_column('expectativas_mes', 'tipo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'debito'::character varying"))
    op.create_index(op.f('ix_budget_planning_ativo'), 'budget_planning', ['ativo'], unique=False)
    op.create_index(op.f('ix_base_padroes_estabelecimento_user'), 'base_padroes', ['padrao_estabelecimento', 'user_id'], unique=False)
    op.drop_index(op.f('ix_base_marcacoes_template_id'), table_name='base_marcacoes_template')
    op.drop_index(op.f('ix_base_marcacoes_id'), table_name='base_marcacoes')
    op.drop_index(op.f('ix_base_grupos_template_id'), table_name='base_grupos_template')
    op.drop_index(op.f('ix_base_grupos_config_nome_grupo'), table_name='base_grupos_config')
    op.drop_index(op.f('ix_base_expectativas_status'), table_name='base_expectativas')
    op.drop_index(op.f('ix_base_expectativas_id_parcela'), table_name='base_expectativas')
    op.drop_index(op.f('ix_base_expectativas_id'), table_name='base_expectativas')
    op.create_table('user_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('connected_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('view_consolidated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accepted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_relationships_pkey'))
    )
    op.create_table('budget_categorias_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_categorias_config_pkey'))
    )
    op.create_table('bank_format_compatibility_backup_20260109_185955',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('estabelecimento_logo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_busca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nome_exibicao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_logo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('estabelecimento_logo_pkey'))
    )
    op.create_table('base_padroes_backup_20260114_144652',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('padrao_estabelecimento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('padrao_num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contagem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_medio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('desvio_padrao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('coef_variacao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('percentual_consistencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confianca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grupo_sugerido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subgrupo_sugerido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo_gasto_sugerido', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('faixa_valor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('segmentado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exemplos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('categoria_geral_sugerida', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('error_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_pt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technical_details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suggested_action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('error_codes_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_table('budget_planning_backup_20260115_204445',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mes_referencia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_planejado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_medio_3_meses', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tabela', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dados_antes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dados_depois', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_table('budget_planning_backup_20260115_204836',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mes_referencia', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_planejado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_medio_3_meses', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('plano_compromissos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('valor_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('meses_restantes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('plano_compromissos_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plano_compromissos_pkey'))
    )
    op.create_index(op.f('ix_plano_compromissos_user_id'), 'plano_compromissos', ['user_id'], unique=False)
    op.create_table('grupo_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('grupo_config_pkey'))
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_table('duplicados_temp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('IdTransacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Estabelecimento', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('origem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('motivo_duplicacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('duplicados_temp_pkey'))
    )
    op.create_table('ignorar_estabelecimentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ignorar_estabelecimentos_pkey'))
    )
    # ### end Alembic commands ###
