"""add_modo_reajuste_to_user_financial_profile

Revision ID: 85375a56914c
Revises: 43105e4ec502
Create Date: 2026-03-02 00:40:04.334466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85375a56914c'
down_revision: Union[str, Sequence[str], None] = '43105e4ec502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_financial_profile', sa.Column('modo_reajuste', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_financial_profile', 'modo_reajuste')
    # ### end Alembic commands ###
