"""Add composite indexes to journal_entries

Revision ID: b52feac5cd7f
Revises: f1200dd073a8
Create Date: 2026-03-08 22:34:02.423345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52feac5cd7f'
down_revision: Union[str, Sequence[str], None] = 'f1200dd073a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_je_user_ignorar_mesfatura', 'journal_entries', ['user_id', 'IgnorarDashboard', 'MesFatura'], unique=False)
    op.create_index('idx_je_user_mesfatura', 'journal_entries', ['user_id', 'MesFatura'], unique=False)
    op.create_index('idx_je_user_mesfatura_cat_valor', 'journal_entries', ['user_id', 'MesFatura', 'CategoriaGeral', 'Valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_je_user_mesfatura_cat_valor', table_name='journal_entries')
    op.drop_index('idx_je_user_mesfatura', table_name='journal_entries')
    op.drop_index('idx_je_user_ignorar_mesfatura', table_name='journal_entries')
    # ### end Alembic commands ###
