"""Add plano_cashflow_mes table

Revision ID: bbc24ab11c33
Revises: b52feac5cd7f
Create Date: 2026-03-08 23:15:42.658017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc24ab11c33'
down_revision: Union[str, Sequence[str], None] = 'b52feac5cd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_cashflow_mes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.String(length=7), nullable=False),
    sa.Column('renda_realizada', sa.Float(), nullable=True),
    sa.Column('gastos_realizados', sa.Float(), nullable=True),
    sa.Column('investimentos_realizados', sa.Float(), nullable=True),
    sa.Column('renda_esperada', sa.Float(), nullable=True),
    sa.Column('gastos_recorrentes', sa.Float(), nullable=True),
    sa.Column('extras_creditos', sa.Float(), nullable=True),
    sa.Column('extras_debitos', sa.Float(), nullable=True),
    sa.Column('renda_usada', sa.Float(), nullable=True),
    sa.Column('total_gastos', sa.Float(), nullable=True),
    sa.Column('aporte_planejado', sa.Float(), nullable=True),
    sa.Column('aporte_usado', sa.Float(), nullable=True),
    sa.Column('use_realizado', sa.Boolean(), nullable=True),
    sa.Column('status_mes', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invalidated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ano', 'mes', name='uq_plano_cashflow_mes')
    )
    op.create_index('idx_plano_cashflow_mes_user_ano', 'plano_cashflow_mes', ['user_id', 'ano'], unique=False)
    op.create_index(op.f('ix_plano_cashflow_mes_id'), 'plano_cashflow_mes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plano_cashflow_mes_id'), table_name='plano_cashflow_mes')
    op.drop_index('idx_plano_cashflow_mes_user_ano', table_name='plano_cashflow_mes')
    op.drop_table('plano_cashflow_mes')
    # ### end Alembic commands ###
