"""add_crescimento_gastos

Revision ID: f1200dd073a8
Revises: 85375a56914c
Create Date: 2026-03-02 00:52:42.174926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1200dd073a8'
down_revision: Union[str, Sequence[str], None] = '85375a56914c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_financial_profile', sa.Column('crescimento_gastos', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_financial_profile', 'crescimento_gastos')
    # ### end Alembic commands ###
