"""initial_schema

Revision ID: f6f307855c81
Revises: 
Create Date: 2026-01-22 19:33:34.068602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f307855c81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_format_compatibility_backup_20260109_185955')
    op.drop_index(op.f('idx_audit_user'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_estabelecimento_logo_nome_busca'), table_name='estabelecimento_logo')
    op.drop_table('estabelecimento_logo')
    op.drop_table('base_padroes_backup_20260114_144652')
    op.drop_table('budget_planning_backup_20260115_204445')
    op.drop_index(op.f('idx_budget_categorias_user'), table_name='budget_categorias_config')
    op.drop_table('budget_categorias_config')
    op.drop_index(op.f('ix_duplicados_temp_IdTransacao'), table_name='duplicados_temp')
    op.drop_table('duplicados_temp')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_user_relationships_connected_user_id'), table_name='user_relationships')
    op.drop_index(op.f('ix_user_relationships_user_id'), table_name='user_relationships')
    op.drop_table('user_relationships')
    op.drop_table('error_codes')
    op.drop_table('categories')
    op.drop_table('budget_planning_backup_20260115_204836')
    op.drop_table('ignorar_estabelecimentos')
    op.drop_index(op.f('ix_grupo_config_nome'), table_name='grupo_config')
    op.drop_table('grupo_config')
    op.alter_column('bank_format_compatibility', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('bank_format_compatibility', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bank_format_compatibility', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_bank_format_compatibility_id'), 'bank_format_compatibility', ['id'], unique=False)
    op.alter_column('base_grupos_config', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('base_grupos_config', 'nome_grupo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('base_grupos_config', 'tipo_gasto_padrao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('base_grupos_config', 'categoria_geral',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_base_grupos_config_id'), 'base_grupos_config', ['id'], unique=False)
    op.create_index(op.f('ix_base_grupos_config_nome_grupo'), 'base_grupos_config', ['nome_grupo'], unique=True)
    op.create_index(op.f('ix_base_marcacoes_id'), 'base_marcacoes', ['id'], unique=False)
    op.drop_column('base_marcacoes', 'CategoriaGeral')
    op.alter_column('base_padroes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('base_padroes', 'valor_medio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('base_padroes', 'valor_min',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'valor_max',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'desvio_padrao',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'coef_variacao',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'data_criacao',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_base_padroes_user_id'), table_name='base_padroes')
    op.create_index(op.f('ix_base_padroes_id'), 'base_padroes', ['id'], unique=False)
    op.create_index(op.f('ix_base_padroes_user_id'), 'base_padroes', ['user_id'], unique=False)
    op.drop_constraint(None, 'base_padroes', type_='foreignkey')
    op.alter_column('base_parcelas', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('base_parcelas', 'id_parcela',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('base_parcelas', 'estabelecimento_base',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('base_parcelas', 'valor_parcela',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('base_parcelas', 'qtd_parcelas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('base_parcelas', 'categoria_geral_sugerida',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_parcelas_user'), table_name='base_parcelas')
    op.drop_index(op.f('ix_base_parcelas_id_parcela'), table_name='base_parcelas')
    op.create_index(op.f('ix_base_parcelas_id_parcela'), 'base_parcelas', ['id_parcela'], unique=False)
    op.create_index(op.f('ix_base_parcelas_id'), 'base_parcelas', ['id'], unique=False)
    op.create_index(op.f('ix_base_parcelas_user_id'), 'base_parcelas', ['user_id'], unique=False)
    op.alter_column('budget_planning', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('budget_planning', 'valor_planejado',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('budget_planning', 'valor_medio_3_meses',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('budget_planning', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('budget_planning', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_budget_planning_id'), 'budget_planning', ['id'], unique=False)
    op.create_index(op.f('ix_budget_planning_mes_referencia'), 'budget_planning', ['mes_referencia'], unique=False)
    op.create_index(op.f('ix_budget_planning_user_id'), 'budget_planning', ['user_id'], unique=False)
    op.drop_index(op.f('ix_investimentos_aportes_extraordinarios_user_id'), table_name='investimentos_aportes_extraordinarios')
    op.drop_column('investimentos_aportes_extraordinarios', 'user_id')
    op.drop_index(op.f('ix_investimentos_historico_user_id'), table_name='investimentos_historico')
    op.drop_column('investimentos_historico', 'user_id')
    op.create_index(op.f('ix_investimentos_portfolio_ano'), 'investimentos_portfolio', ['ano'], unique=False)
    op.create_index(op.f('ix_investimentos_portfolio_anomes'), 'investimentos_portfolio', ['anomes'], unique=False)
    op.alter_column('journal_entries', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('journal_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('journal_entries', 'Data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'Estabelecimento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'Valor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('journal_entries', 'ValorPositivo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('journal_entries', 'TipoTransacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'TipoGasto',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'GRUPO',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'SUBGRUPO',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'CategoriaGeral',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'IdTransacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'IdParcela',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'EstabelecimentoBase',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'arquivo_origem',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'banco_origem',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'tipodocumento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'origem_classificacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'MesFatura',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('journal_entries', 'NomeCartao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_journal_banco_origem'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_entries_id_transacao_temp'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_entries_upload_history_id'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_idparcela'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_idtransacao'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_nomecartao'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_origem_class'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_tipodocumento'), table_name='journal_entries')
    op.drop_index(op.f('idx_journal_user_id'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_IdTransacao'), 'journal_entries', ['IdTransacao'], unique=True)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_session_id'), 'journal_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_upload_history_id'), 'journal_entries', ['upload_history_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'upload_history', ['upload_history_id'], ['id'])
    op.alter_column('preview_transacoes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('preview_transacoes', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('preview_transacoes', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'banco',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('preview_transacoes', 'cartao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'nome_arquivo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('preview_transacoes', 'mes_fatura',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'data',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('preview_transacoes', 'lancamento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('preview_transacoes', 'valor',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('preview_transacoes', 'data_criacao',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'IdTransacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'IdParcela',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'EstabelecimentoBase',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'ValorPositivo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'TipoTransacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'GRUPO',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'SUBGRUPO',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'TipoGasto',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'CategoriaGeral',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'origem_classificacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'padrao_buscado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'MarcacaoIA',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_preview_id_parcela'), table_name='preview_transacoes')
    op.drop_index(op.f('idx_preview_id_transacao'), table_name='preview_transacoes')
    op.drop_index(op.f('idx_preview_origem'), table_name='preview_transacoes')
    op.drop_index(op.f('idx_preview_session'), table_name='preview_transacoes')
    op.drop_index(op.f('idx_preview_user'), table_name='preview_transacoes')
    op.create_index(op.f('ix_preview_transacoes_IdParcela'), 'preview_transacoes', ['IdParcela'], unique=False)
    op.create_index(op.f('ix_preview_transacoes_IdTransacao'), 'preview_transacoes', ['IdTransacao'], unique=False)
    op.create_index(op.f('ix_preview_transacoes_id'), 'preview_transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_preview_transacoes_session_id'), 'preview_transacoes', ['session_id'], unique=False)
    op.create_index(op.f('ix_preview_transacoes_user_id'), 'preview_transacoes', ['user_id'], unique=False)
    op.drop_constraint(None, 'preview_transacoes', type_='foreignkey')
    op.drop_column('preview_transacoes', 'ValidarIA')
    op.drop_column('preview_transacoes', 'TemParcela')
    op.drop_column('preview_transacoes', 'IgnorarDashboard')
    op.alter_column('screen_visibility', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('screen_visibility', 'screen_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('screen_visibility', 'screen_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('screen_visibility', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'P'"))
    op.alter_column('screen_visibility', 'icon',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'parent_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('screen_visibility', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_screen_visibility_id'), 'screen_visibility', ['id'], unique=False)
    op.create_index(op.f('ix_screen_visibility_screen_key'), 'screen_visibility', ['screen_key'], unique=True)
    op.alter_column('transacoes_exclusao', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('transacoes_exclusao', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transacoes_exclusao', 'tipo_documento',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'ambos'"))
    op.alter_column('transacoes_exclusao', 'acao',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'EXCLUIR'"))
    op.create_index(op.f('ix_transacoes_exclusao_nome_transacao'), 'transacoes_exclusao', ['nome_transacao'], unique=False)
    op.alter_column('upload_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('upload_history', 'classification_stats',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('upload_history', 'balance_validation',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_upload_history_session_id'), table_name='upload_history')
    op.drop_index(op.f('idx_upload_history_status'), table_name='upload_history')
    op.drop_index(op.f('idx_upload_history_user_id'), table_name='upload_history')
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_index(op.f('ix_upload_history_session_id'), 'upload_history', ['session_id'], unique=True)
    op.create_index(op.f('ix_upload_history_status'), 'upload_history', ['status'], unique=False)
    op.create_index(op.f('ix_upload_history_user_id'), 'upload_history', ['user_id'], unique=False)
    op.alter_column('users', 'ativo',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'ativo',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_index(op.f('ix_upload_history_user_id'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_status'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_session_id'), table_name='upload_history')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.create_index(op.f('idx_upload_history_user_id'), 'upload_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_upload_history_status'), 'upload_history', ['status'], unique=False)
    op.create_index(op.f('idx_upload_history_session_id'), 'upload_history', ['session_id'], unique=False)
    op.alter_column('upload_history', 'balance_validation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('upload_history', 'classification_stats',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('upload_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_transacoes_exclusao_nome_transacao'), table_name='transacoes_exclusao')
    op.alter_column('transacoes_exclusao', 'acao',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'EXCLUIR'"))
    op.alter_column('transacoes_exclusao', 'tipo_documento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'ambos'"))
    op.alter_column('transacoes_exclusao', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transacoes_exclusao', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_screen_visibility_screen_key'), table_name='screen_visibility')
    op.drop_index(op.f('ix_screen_visibility_id'), table_name='screen_visibility')
    op.alter_column('screen_visibility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('screen_visibility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('screen_visibility', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'parent_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'icon',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('screen_visibility', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'P'"))
    op.alter_column('screen_visibility', 'screen_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('screen_visibility', 'screen_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('screen_visibility', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('preview_transacoes', sa.Column('IgnorarDashboard', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('preview_transacoes', sa.Column('TemParcela', sa.INTEGER(), nullable=True))
    op.add_column('preview_transacoes', sa.Column('ValidarIA', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'preview_transacoes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_preview_transacoes_user_id'), table_name='preview_transacoes')
    op.drop_index(op.f('ix_preview_transacoes_session_id'), table_name='preview_transacoes')
    op.drop_index(op.f('ix_preview_transacoes_id'), table_name='preview_transacoes')
    op.drop_index(op.f('ix_preview_transacoes_IdTransacao'), table_name='preview_transacoes')
    op.drop_index(op.f('ix_preview_transacoes_IdParcela'), table_name='preview_transacoes')
    op.create_index(op.f('idx_preview_user'), 'preview_transacoes', ['user_id'], unique=False)
    op.create_index(op.f('idx_preview_session'), 'preview_transacoes', ['session_id'], unique=False)
    op.create_index(op.f('idx_preview_origem'), 'preview_transacoes', ['origem_classificacao'], unique=False)
    op.create_index(op.f('idx_preview_id_transacao'), 'preview_transacoes', ['IdTransacao'], unique=False)
    op.create_index(op.f('idx_preview_id_parcela'), 'preview_transacoes', ['IdParcela'], unique=False)
    op.alter_column('preview_transacoes', 'MarcacaoIA',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'padrao_buscado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'origem_classificacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'CategoriaGeral',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'TipoGasto',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'SUBGRUPO',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'GRUPO',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'TipoTransacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'ValorPositivo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'EstabelecimentoBase',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'IdParcela',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'IdTransacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'data_criacao',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'valor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('preview_transacoes', 'lancamento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('preview_transacoes', 'data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('preview_transacoes', 'mes_fatura',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'nome_arquivo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('preview_transacoes', 'cartao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'banco',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('preview_transacoes', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('preview_transacoes', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('preview_transacoes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_upload_history_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_session_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_IdTransacao'), table_name='journal_entries')
    op.create_index(op.f('idx_journal_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_index(op.f('idx_journal_tipodocumento'), 'journal_entries', ['tipodocumento'], unique=False)
    op.create_index(op.f('idx_journal_origem_class'), 'journal_entries', ['origem_classificacao'], unique=False)
    op.create_index(op.f('idx_journal_nomecartao'), 'journal_entries', ['NomeCartao'], unique=False)
    op.create_index(op.f('idx_journal_idtransacao'), 'journal_entries', ['IdTransacao'], unique=False)
    op.create_index(op.f('idx_journal_idparcela'), 'journal_entries', ['IdParcela'], unique=False)
    op.create_index(op.f('idx_journal_entries_upload_history_id'), 'journal_entries', ['upload_history_id'], unique=False)
    op.create_index(op.f('idx_journal_entries_id_transacao_temp'), 'journal_entries', ['IdTransacao'], unique=False)
    op.create_index(op.f('idx_journal_banco_origem'), 'journal_entries', ['banco_origem'], unique=False)
    op.alter_column('journal_entries', 'NomeCartao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('journal_entries', 'MesFatura',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'origem_classificacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'tipodocumento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'banco_origem',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'arquivo_origem',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'EstabelecimentoBase',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'IdParcela',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'IdTransacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('journal_entries', 'CategoriaGeral',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'SUBGRUPO',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'GRUPO',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'TipoGasto',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'TipoTransacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('journal_entries', 'ValorPositivo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('journal_entries', 'Valor',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
    op.alter_column('journal_entries', 'Estabelecimento',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('journal_entries', 'Data',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('journal_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('journal_entries', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_investimentos_portfolio_anomes'), table_name='investimentos_portfolio')
    op.drop_index(op.f('ix_investimentos_portfolio_ano'), table_name='investimentos_portfolio')
    op.add_column('investimentos_historico', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_investimentos_historico_user_id'), 'investimentos_historico', ['user_id'], unique=False)
    op.add_column('investimentos_aportes_extraordinarios', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_investimentos_aportes_extraordinarios_user_id'), 'investimentos_aportes_extraordinarios', ['user_id'], unique=False)
    op.drop_index(op.f('ix_budget_planning_user_id'), table_name='budget_planning')
    op.drop_index(op.f('ix_budget_planning_mes_referencia'), table_name='budget_planning')
    op.drop_index(op.f('ix_budget_planning_id'), table_name='budget_planning')
    op.alter_column('budget_planning', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('budget_planning', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('budget_planning', 'valor_medio_3_meses',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('budget_planning', 'valor_planejado',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('budget_planning', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_base_parcelas_user_id'), table_name='base_parcelas')
    op.drop_index(op.f('ix_base_parcelas_id'), table_name='base_parcelas')
    op.drop_index(op.f('ix_base_parcelas_id_parcela'), table_name='base_parcelas')
    op.create_index(op.f('ix_base_parcelas_id_parcela'), 'base_parcelas', ['id_parcela'], unique=1)
    op.create_index(op.f('idx_parcelas_user'), 'base_parcelas', ['user_id'], unique=False)
    op.alter_column('base_parcelas', 'categoria_geral_sugerida',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('base_parcelas', 'qtd_parcelas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('base_parcelas', 'valor_parcela',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('base_parcelas', 'estabelecimento_base',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('base_parcelas', 'id_parcela',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('base_parcelas', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_foreign_key(None, 'base_padroes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_base_padroes_user_id'), table_name='base_padroes')
    op.drop_index(op.f('ix_base_padroes_id'), table_name='base_padroes')
    op.create_index(op.f('idx_base_padroes_user_id'), 'base_padroes', ['user_id'], unique=False)
    op.alter_column('base_padroes', 'data_criacao',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('base_padroes', 'coef_variacao',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'desvio_padrao',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'valor_max',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'valor_min',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('base_padroes', 'valor_medio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('base_padroes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('base_marcacoes', sa.Column('CategoriaGeral', sa.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_base_marcacoes_id'), table_name='base_marcacoes')
    op.drop_index(op.f('ix_base_grupos_config_nome_grupo'), table_name='base_grupos_config')
    op.drop_index(op.f('ix_base_grupos_config_id'), table_name='base_grupos_config')
    op.alter_column('base_grupos_config', 'categoria_geral',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('base_grupos_config', 'tipo_gasto_padrao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('base_grupos_config', 'nome_grupo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('base_grupos_config', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_bank_format_compatibility_id'), table_name='bank_format_compatibility')
    op.alter_column('bank_format_compatibility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bank_format_compatibility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('bank_format_compatibility', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('grupo_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('icone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cor', sa.VARCHAR(length=7), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('ordem', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_config_nome'), 'grupo_config', ['nome'], unique=1)
    op.create_table('ignorar_estabelecimentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('budget_planning_backup_20260115_204836',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('grupo', sa.TEXT(), nullable=True),
    sa.Column('mes_referencia', sa.TEXT(), nullable=True),
    sa.Column('valor_planejado', sa.NUMERIC(), nullable=True),
    sa.Column('valor_medio_3_meses', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('tipo', sa.TEXT(), nullable=False),
    sa.Column('ativo', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("tipo IN ('GRUPO', 'SUBGRUPO', 'TIPOGASTO')), ativo INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(nome, tipo)"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'tipo')
    )
    op.create_table('error_codes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=False),
    sa.Column('message_pt', sa.TEXT(), nullable=False),
    sa.Column('technical_details', sa.TEXT(), nullable=True),
    sa.Column('suggested_action', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.TEXT(), server_default=sa.text("'error'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_relationships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('connected_user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('view_consolidated', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('accepted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_relationships_user_id'), 'user_relationships', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_relationships_connected_user_id'), 'user_relationships', ['connected_user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('revoked', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=1)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('duplicados_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('IdTransacao', sa.VARCHAR(length=64), nullable=False),
    sa.Column('Data', sa.VARCHAR(length=10), nullable=True),
    sa.Column('Estabelecimento', sa.TEXT(), nullable=True),
    sa.Column('Valor', sa.FLOAT(), nullable=True),
    sa.Column('origem', sa.VARCHAR(length=50), nullable=True),
    sa.Column('motivo_duplicacao', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicados_temp_IdTransacao'), 'duplicados_temp', ['IdTransacao'], unique=False)
    op.create_table('budget_categorias_config',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ordem', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'nome')
    )
    op.create_index(op.f('idx_budget_categorias_user'), 'budget_categorias_config', ['user_id'], unique=False)
    op.create_table('budget_planning_backup_20260115_204445',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('grupo', sa.TEXT(), nullable=True),
    sa.Column('mes_referencia', sa.TEXT(), nullable=True),
    sa.Column('valor_planejado', sa.NUMERIC(), nullable=True),
    sa.Column('valor_medio_3_meses', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    op.create_table('base_padroes_backup_20260114_144652',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('padrao_estabelecimento', sa.TEXT(), nullable=True),
    sa.Column('padrao_num', sa.TEXT(), nullable=True),
    sa.Column('contagem', sa.INTEGER(), nullable=True),
    sa.Column('valor_medio', sa.REAL(), nullable=True),
    sa.Column('valor_min', sa.REAL(), nullable=True),
    sa.Column('valor_max', sa.REAL(), nullable=True),
    sa.Column('desvio_padrao', sa.REAL(), nullable=True),
    sa.Column('coef_variacao', sa.REAL(), nullable=True),
    sa.Column('percentual_consistencia', sa.INTEGER(), nullable=True),
    sa.Column('confianca', sa.TEXT(), nullable=True),
    sa.Column('grupo_sugerido', sa.TEXT(), nullable=True),
    sa.Column('subgrupo_sugerido', sa.TEXT(), nullable=True),
    sa.Column('tipo_gasto_sugerido', sa.TEXT(), nullable=True),
    sa.Column('faixa_valor', sa.TEXT(), nullable=True),
    sa.Column('segmentado', sa.INTEGER(), nullable=True),
    sa.Column('exemplos', sa.TEXT(), nullable=True),
    sa.Column('data_criacao', sa.NUMERIC(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('categoria_geral_sugerida', sa.TEXT(), nullable=True)
    )
    op.create_table('estabelecimento_logo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_busca', sa.VARCHAR(length=200), nullable=False),
    sa.Column('nome_exibicao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('arquivo_logo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estabelecimento_logo_nome_busca'), 'estabelecimento_logo', ['nome_busca'], unique=1)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('acao', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tabela', sa.VARCHAR(length=50), nullable=False),
    sa.Column('registro_id', sa.INTEGER(), nullable=True),
    sa.Column('dados_antes', sa.TEXT(), nullable=True),
    sa.Column('dados_depois', sa.TEXT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_audit_user'), 'audit_log', ['user_id'], unique=False)
    op.create_table('bank_format_compatibility_backup_20260109_185955',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('bank_name', sa.TEXT(), nullable=True),
    sa.Column('file_format', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('updated_at', sa.NUMERIC(), nullable=True)
    )
    # ### end Alembic commands ###
